apiVersion: v1
kind: Secret
metadata:
  name: ts-assurance-mysql
type: Opaque
stringData:
  ASSURANCE_MYSQL_HOST: "tsdb-mysql-leader"
  ASSURANCE_MYSQL_PORT: "3306"
  ASSURANCE_MYSQL_DATABASE: "ts"
  ASSURANCE_MYSQL_USER: "ts"
  ASSURANCE_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-auth-mysql
type: Opaque
stringData:
  AUTH_MYSQL_HOST: "tsdb-mysql-leader"
  AUTH_MYSQL_PORT: "3306"
  AUTH_MYSQL_DATABASE: "ts"
  AUTH_MYSQL_USER: "ts"
  AUTH_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-config-mysql
type: Opaque
stringData:
  CONFIG_MYSQL_HOST: "tsdb-mysql-leader"
  CONFIG_MYSQL_PORT: "3306"
  CONFIG_MYSQL_DATABASE: "ts"
  CONFIG_MYSQL_USER: "ts"
  CONFIG_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-consign-price-mysql
type: Opaque
stringData:
  CONSIGN_PRICE_MYSQL_HOST: "tsdb-mysql-leader"
  CONSIGN_PRICE_MYSQL_PORT: "3306"
  CONSIGN_PRICE_MYSQL_DATABASE: "ts"
  CONSIGN_PRICE_MYSQL_USER: "ts"
  CONSIGN_PRICE_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-consign-mysql
type: Opaque
stringData:
  CONSIGN_MYSQL_HOST: "tsdb-mysql-leader"
  CONSIGN_MYSQL_PORT: "3306"
  CONSIGN_MYSQL_DATABASE: "ts"
  CONSIGN_MYSQL_USER: "ts"
  CONSIGN_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-contacts-mysql
type: Opaque
stringData:
  CONTACTS_MYSQL_HOST: "tsdb-mysql-leader"
  CONTACTS_MYSQL_PORT: "3306"
  CONTACTS_MYSQL_DATABASE: "ts"
  CONTACTS_MYSQL_USER: "ts"
  CONTACTS_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-delivery-mysql
type: Opaque
stringData:
  DELIVERY_MYSQL_HOST: "tsdb-mysql-leader"
  DELIVERY_MYSQL_PORT: "3306"
  DELIVERY_MYSQL_DATABASE: "ts"
  DELIVERY_MYSQL_USER: "ts"
  DELIVERY_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-food-mysql
type: Opaque
stringData:
  FOOD_MYSQL_HOST: "tsdb-mysql-leader"
  FOOD_MYSQL_PORT: "3306"
  FOOD_MYSQL_DATABASE: "ts"
  FOOD_MYSQL_USER: "ts"
  FOOD_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-food-delivery-mysql
type: Opaque
stringData:
  FOOD_DELIVERY_MYSQL_HOST: "tsdb-mysql-leader"
  FOOD_DELIVERY_MYSQL_PORT: "3306"
  FOOD_DELIVERY_MYSQL_DATABASE: "ts"
  FOOD_DELIVERY_MYSQL_USER: "ts"
  FOOD_DELIVERY_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-inside-payment-mysql
type: Opaque
stringData:
  INSIDE_PAYMENT_MYSQL_HOST: "tsdb-mysql-leader"
  INSIDE_PAYMENT_MYSQL_PORT: "3306"
  INSIDE_PAYMENT_MYSQL_DATABASE: "ts"
  INSIDE_PAYMENT_MYSQL_USER: "ts"
  INSIDE_PAYMENT_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-notification-mysql
type: Opaque
stringData:
  NOTIFICATION_MYSQL_HOST: "tsdb-mysql-leader"
  NOTIFICATION_MYSQL_PORT: "3306"
  NOTIFICATION_MYSQL_DATABASE: "ts"
  NOTIFICATION_MYSQL_USER: "ts"
  NOTIFICATION_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-order-other-mysql
type: Opaque
stringData:
  ORDER_OTHER_MYSQL_HOST: "tsdb-mysql-leader"
  ORDER_OTHER_MYSQL_PORT: "3306"
  ORDER_OTHER_MYSQL_DATABASE: "ts"
  ORDER_OTHER_MYSQL_USER: "ts"
  ORDER_OTHER_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-order-mysql
type: Opaque
stringData:
  ORDER_MYSQL_HOST: "tsdb-mysql-leader"
  ORDER_MYSQL_PORT: "3306"
  ORDER_MYSQL_DATABASE: "ts"
  ORDER_MYSQL_USER: "ts"
  ORDER_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-payment-mysql
type: Opaque
stringData:
  PAYMENT_MYSQL_HOST: "tsdb-mysql-leader"
  PAYMENT_MYSQL_PORT: "3306"
  PAYMENT_MYSQL_DATABASE: "ts"
  PAYMENT_MYSQL_USER: "ts"
  PAYMENT_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-price-mysql
type: Opaque
stringData:
  PRICE_MYSQL_HOST: "tsdb-mysql-leader"
  PRICE_MYSQL_PORT: "3306"
  PRICE_MYSQL_DATABASE: "ts"
  PRICE_MYSQL_USER: "ts"
  PRICE_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-route-mysql
type: Opaque
stringData:
  ROUTE_MYSQL_HOST: "tsdb-mysql-leader"
  ROUTE_MYSQL_PORT: "3306"
  ROUTE_MYSQL_DATABASE: "ts"
  ROUTE_MYSQL_USER: "ts"
  ROUTE_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-security-mysql
type: Opaque
stringData:
  SECURITY_MYSQL_HOST: "tsdb-mysql-leader"
  SECURITY_MYSQL_PORT: "3306"
  SECURITY_MYSQL_DATABASE: "ts"
  SECURITY_MYSQL_USER: "ts"
  SECURITY_MYSQL_PASSWORD: "Ts_123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-station-food-mysql
type: Opaque
stringData:
  STATION_FOOD_MYSQL_HOST: "tsdb-mysql-leader"
  STATION_FOOD_MYSQL_PORT: "3306"
  STATION_FOOD_MYSQL_DATABASE: "ts"
  STATION_FOOD_MYSQL_USER: "ts"
  STATION_FOOD_MYSQL_PASSWORD: "Ts_123456"
---
